// <auto-generated />
using System;
using Estacionamento.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estacionamento.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Estacionamento.Models.TabelaPrecoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FinalVigencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinutoTolerancia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecoPorHora")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorHoraAdicional")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TabelasPreco");
                });

            modelBuilder.Entity("Estacionamento.Models.VeiculoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duracao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Estacionado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HorarioChegada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HorarioSaida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Proprietario")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TempoCobrado")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorAPagar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
